Repository WildCodeSchool/orleans-0219-php-escape, pull requests merged in 2019-04, with the labels that each got.

#2 Navbar
  composer.lock
  public/assets/css/navbar.css
  public/assets/images/navbar/NAVBAR.png
  public/assets/images/navbar/logoprojet2.png
  public/assets/images/navbar/nav2.png
  src/Controller/HomeController.php
  src/View/Home/_navbar.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
  src/View/layoutVisitor.html.twig
Labels: Change requested, Reviewed by PO

#9 Sprint02 us06 footer
  public/assets/css/style.css
  public/assets/images/footer/fb.png
  public/assets/images/footer/footer.png
  public/assets/images/footer/tripadvisor.png
  public/assets/images/footer/twitter.png
  src/View/Home/_footer.html.twig
  src/View/layout.html.twig
  src/View/layoutVisitor.html.twig
Labels: Reviewed by PO

#11 Pull request de la branche dev vers la branche master
  public/assets/css/style.css
  public/assets/images/footer/fb.png
  public/assets/images/footer/footer.png
  public/assets/images/footer/tripadvisor.png
  public/assets/images/footer/twitter.png
  src/View/Home/_footer.html.twig
  src/View/layout.html.twig
  src/View/layoutVisitor.html.twig
Labels: Reviewed by PO

#12 Ajout de la partie Atouts à la HomePage.
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/fonts/ATypewriterForMe.ttf
  public/assets/fonts/BOYCOTT_.TTF
  public/assets/images/295a135aaa6be7e4debb5b8f816a46d5.jpg
  src/View/Home/_navbar.html.twig
  src/View/Home/assets.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
  src/View/layoutVisitor.html.twig
Labels: Corrections Done

#23 The Final Navbar
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/images/favicon.png
  public/assets/images/navbar/NAVBAR.png
  public/assets/images/navbar/NavbarBg.png
  public/assets/images/navbar/logoleaf.png
  public/assets/images/navbar/nav2.png
  src/View/Home/_navbar.html.twig
  src/View/layout.html.twig
  src/View/layoutVisitor.html.twig
Labels: Reviewed by PO

#26 Creation part news
  public/assets/css/style.css
  src/View/Home/_news.html.twig
  src/View/Home/index.html.twig
  src/View/layoutVisitor.html.twig
Labels: Reviewed by PO

#24 Header2
  public/assets/css/style.css
  public/assets/images/background/backButton.webp
  public/assets/images/background/sign2.webp
  public/assets/images/background/woodsignphone.webp
  public/assets/images/tripadvisor/note1.png
  public/assets/images/tripadvisor/note2 .png
  public/assets/images/tripadvisor/tripadvisorLogo.png
  src/View/Home/_header.html.twig
  src/View/layoutVisitor.html.twig
Labels: Corrections Done, Reviewed by PO

#27 repositionnement du footer
  public/assets/css/style.css
  src/View/layout.html.twig
Labels: Reviewed by PO

#15 Dev
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/fonts/ATypewriterForMe.ttf
  public/assets/fonts/BOYCOTT_.TTF
  public/assets/images/295a135aaa6be7e4debb5b8f816a46d5.jpg
  public/assets/images/background/backButton.webp
  public/assets/images/background/sign2.webp
  public/assets/images/background/woodsignphone.webp
  public/assets/images/favicon.png
  public/assets/images/navbar/NAVBAR.png
  public/assets/images/navbar/NavbarBg.png
  public/assets/images/navbar/logoleaf.png
  public/assets/images/navbar/nav2.png
  public/assets/images/tripadvisor/note1.png
  public/assets/images/tripadvisor/note2 .png
  public/assets/images/tripadvisor/tripadvisorLogo.png
  src/View/Home/_header.html.twig
  src/View/Home/_navbar.html.twig
  src/View/Home/_news.html.twig
  src/View/Home/assets.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
  src/View/layoutVisitor.html.twig
Labels: Reviewed by PO

#33 Spit du Header
  public/assets/css/style.css
  src/View/Home/_missionButton.html.twig
  src/View/Home/_title.html.twig
  src/View/Home/_tripadvisor.html.twig
  src/View/Home/index.html.twig
  src/View/layoutVisitor.html.twig
Labels: Reviewed by PO

#35 noms appropriés pour le css navbar
  public/assets/css/style.css
  src/View/Home/_navbar.html.twig
Labels: Reviewed by PO

#36 Ajout bg HomePage
  public/assets/css/style.css
Labels: Reviewed by PO

#37 Creation de la div section News
  public/assets/css/style.css
  src/View/Home/_news.html.twig
Labels: Reviewed by PO

#39 Lestarifs
  public/assets/css/style.css
  src/Controller/PriceController.php
  src/View/Home/_navbar.html.twig
  src/View/Price/index.html.twig
Labels: Reviewed by PO

#38 fix footer + layout
  public/assets/css/style.css
  src/View/Home/_footer.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#40 Lestarifs
  public/assets/css/style.css
  public/assets/images/background-wood-board-parquet.webp
  src/View/Home/assets.html.twig
  src/View/Price/index.html.twig
Labels: Corrections Done, Reviewed by PO

#41 Dev
  public/assets/css/style.css
  public/assets/images/background-wood-board-parquet.webp
  src/Controller/PriceController.php
  src/View/Home/_footer.html.twig
  src/View/Home/_missionButton.html.twig
  src/View/Home/_navbar.html.twig
  src/View/Home/_news.html.twig
  src/View/Home/_title.html.twig
  src/View/Home/_tripadvisor.html.twig
  src/View/Home/assets.html.twig
  src/View/Home/index.html.twig
  src/View/Price/index.html.twig
  src/View/layout.html.twig
  src/View/layoutVisitor.html.twig
Labels: Reviewed by PO

#48 ajout du collapse pour les entreprises et anniversaires
  public/assets/css/style.css
  public/assets/images/feuille.jpg
  public/assets/images/feuille.png
  src/View/Price/index.html.twig
Labels: Reviewed by PO

#51 background modifié
  public/assets/css/style.css
  public/assets/images/background/xv.png
Labels: Reviewed by PO

#52 images missions ajoutées
  public/assets/images/missions/aiguillagefatal.jpg
  public/assets/images/missions/backtothepast.jpg
  public/assets/images/missions/lademeure.jpg
  public/assets/images/missions/latelier.jpg
  public/assets/images/missions/nautilus.jpg
Labels: Reviewed by PO

#53 Modif Opacité
  public/assets/css/style.css
Labels: Reviewed by PO

#54 Chemin des images
  src/View/Home/_tripadvisor.html.twig
Labels: Reviewed by PO
